import {
  AlignmentType,
  Document,
  HeadingLevel,
  Packer,
  Paragraph,
  TextRun,
} from 'docx';
import type { Finding, Scan } from '../types.js';
import { SEVERITY_ORDER } from '../types.js';

export interface ReportInput {
  scan: Scan;
  findings: Finding[];
  generatedBy: string;
}

function p(text: string, opts: { bold?: boolean; size?: number; color?: string } = {}): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({
        text,
        bold: opts.bold,
        size: opts.size ?? 22,
        color: opts.color,
      }),
    ],
  });
}

function heading(text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel]): Paragraph {
  return new Paragraph({ text, heading: level });
}

const SEV_COLORS: Record<string, string> = {
  critical: '991B1B',
  high: 'C2410C',
  medium: '92400E',
  low: '1E40AF',
  info: '4B5563',
};

/**
 * DOCX report generator — same content contract as the PDF generator
 * (executive summary, CVSS estimates, repro steps, remediation, appendix).
 */
export async function generateDocxReport(input: ReportInput): Promise<Buffer> {
  const { scan, findings } = input;
  const sorted = [...findings].sort(
    (a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]
  );
  const counts: Record<string, number> = {};
  for (const f of sorted) counts[f.severity] = (counts[f.severity] ?? 0) + 1;

  const children: Paragraph[] = [
    new Paragraph({ text: 'BugSeek AI', heading: HeadingLevel.TITLE }),
    heading('Security Assessment Report', HeadingLevel.HEADING_1),
    p(`Target: ${scan.targetUrl}`),
    p(`Scan mode: ${scan.mode}`),
    p(`Scan ID: ${scan.id}`),
    p(`Scan date: ${scan.createdAt}`),
    ...(scan.authorizationId ? [p(`Authorization record: ${scan.authorizationId}`)] : []),
    p(`Generated by: ${input.generatedBy}`),
    new Paragraph({ text: '' }),
    heading('Executive Summary', HeadingLevel.HEADING_1),
    p(
      `BugSeek AI performed a ${scan.mode} security assessment of ${scan.targetUrl} and identified ` +
        `${sorted.length} finding(s). CVSS v3.1 scores in this report are heuristic estimates produced by ` +
        `BugSeek's scoring model and should be validated by a human analyst before submission.`
    ),
    p(
      'Severity breakdown: ' +
        ['critical', 'high', 'medium', 'low', 'info'].map((s) => `${s}: ${counts[s] ?? 0}`).join(' · ')
    ),
  ];

  const traps = sorted.filter((f) => f.honeypotSuspect).length;
  if (traps > 0) {
    children.push(
      p(
        `Note: ${traps} observation(s) were flagged as possible honeypots/traps and require manual verification.`,
        { bold: true, color: '92400E' }
      )
    );
  }

  children.push(new Paragraph({ text: '' }), heading('Findings', HeadingLevel.HEADING_1));

  if (sorted.length === 0) {
    children.push(p('No findings were identified during this scan.'));
  }

  sorted.forEach((f, idx) => {
    children.push(
      heading(`${idx + 1}. ${f.title}`, HeadingLevel.HEADING_2),
      p(
        `Severity: ${f.severity.toUpperCase()}${f.cvssScore != null ? `  ·  CVSS: ${f.cvssScore.toFixed(1)}` : ''}  ·  Confidence: ${f.confidence}`,
        { bold: true, color: SEV_COLORS[f.severity] ?? '4B5563' }
      )
    );
    if (f.honeypotSuspect) {
      children.push(
        p(
          `⚠ Possible trap (trap probability ${(f.trapProbability * 100).toFixed(0)}%) — verify manually before reporting.`,
          { bold: true, color: '92400E' }
        )
      );
    }
    children.push(p(f.description));
    if (f.cvssVector) children.push(p(`CVSS vector: ${f.cvssVector} (estimate)`, { size: 18, color: '6B7280' }));
    if (f.location) children.push(p('Location:', { bold: true }), p(f.location));
    if (f.evidence) children.push(p('Evidence (redacted):', { bold: true }), p(f.evidence));
    if (f.reproSteps.length > 0) {
      children.push(p('Reproduction steps:', { bold: true }));
      f.reproSteps.forEach((s, i) => children.push(p(`${i + 1}. ${s}`)));
    }
    children.push(p('Remediation:', { bold: true }), p(f.remediation));
    if (f.suggestedFix) {
      children.push(
        p('Suggested fix (AI-generated — review before applying):', { bold: true }),
        p(f.suggestedFix)
      );
    }
    if (f.references.length > 0) {
      children.push(p('References:', { bold: true }));
      f.references.forEach((r) => children.push(p(r, { color: '1E40AF' })));
    }
    children.push(new Paragraph({ text: '' }));
  });

  children.push(
    heading('Appendix — Methodology & Legal', HeadingLevel.HEADING_1),
    p(
      'This assessment was performed by BugSeek AI, an AI-assisted security reconnaissance tool. ' +
        'Active tests were rate-limited, scope-restricted to the user-confirmed target, and executed only ' +
        'after explicit authorization confirmation (see authorization record above). Sensitive data discovered ' +
        'during testing is redacted before storage and never exfiltrated.'
    ),
    p(
      'Disclaimer: automated findings require human verification before submission to bug bounty programs. ' +
        'BugSeek AI is intended for authorized security testing only; users accept liability for their testing activities.'
    )
  );

  const doc = new Document({
    sections: [{ children }],
    title: `BugSeek AI Security Report — ${scan.targetUrl}`,
    creator: 'BugSeek AI',
  });
  return Buffer.from(await Packer.toBuffer(doc));
}
