import type { Finding, Scan } from '../types.js';
import { SEVERITY_ORDER } from '../types.js';

export interface ReportInput {
  scan: Scan;
  findings: Finding[];
  generatedBy: string;
}

/** Markdown report — the free-tier format and the base for bounty-platform templates. */
export function generateMarkdownReport(input: ReportInput): string {
  const { scan, findings } = input;
  const sorted = [...findings].sort(
    (a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]
  );
  const counts: Record<string, number> = {};
  for (const f of sorted) counts[f.severity] = (counts[f.severity] ?? 0) + 1;

  const lines: string[] = [
    '# BugSeek AI — Security Assessment Report',
    '',
    `- **Target:** ${scan.targetUrl}`,
    `- **Scan mode:** ${scan.mode}`,
    `- **Scan ID:** ${scan.id}`,
    `- **Scan date:** ${scan.createdAt}`,
    ...(scan.authorizationId ? [`- **Authorization record:** ${scan.authorizationId}`] : []),
    `- **Generated by:** ${input.generatedBy}`,
    '',
    '## Executive Summary',
    '',
    `BugSeek AI performed a ${scan.mode} security assessment of ${scan.targetUrl} and identified ` +
      `${sorted.length} finding(s). CVSS v3.1 scores are heuristic estimates and should be validated ` +
      `by a human analyst before submission.`,
    '',
    '**Severity breakdown:** ' +
      ['critical', 'high', 'medium', 'low', 'info'].map((s) => `${s}: ${counts[s] ?? 0}`).join(' · '),
    '',
  ];

  const traps = sorted.filter((f) => f.honeypotSuspect).length;
  if (traps > 0) {
    lines.push(
      `> ⚠ **${traps} observation(s) were flagged as possible honeypots/traps** and require manual verification.`,
      ''
    );
  }

  lines.push('## Findings', '');
  if (sorted.length === 0) {
    lines.push('No findings were identified during this scan.', '');
  }
  sorted.forEach((f, idx) => {
    lines.push(
      `### ${idx + 1}. ${f.title}`,
      '',
      `**Severity:** ${f.severity.toUpperCase()}${f.cvssScore != null ? ` · **CVSS:** ${f.cvssScore.toFixed(1)}` : ''} · **Confidence:** ${f.confidence}`,
      ''
    );
    if (f.honeypotSuspect) {
      lines.push(
        `> ⚠ **Possible trap** (trap probability ${(f.trapProbability * 100).toFixed(0)}%) — verify manually before reporting.`,
        ''
      );
    }
    lines.push(f.description, '');
    if (f.cvssVector) lines.push(`\`CVSS vector: ${f.cvssVector} (estimate)\``, '');
    if (f.location) lines.push(`**Location:** ${f.location}`, '');
    if (f.evidence) lines.push('**Evidence (redacted):**', '', '```', f.evidence, '```', '');
    if (f.reproSteps.length > 0) {
      lines.push('**Reproduction steps:**', '');
      f.reproSteps.forEach((s, i) => lines.push(`${i + 1}. ${s}`));
      lines.push('');
    }
    lines.push('**Remediation:**', '', f.remediation, '');
    if (f.suggestedFix) {
      lines.push(
        '**Suggested fix (AI-generated — review before applying):**',
        '',
        '```',
        f.suggestedFix,
        '```',
        ''
      );
    }
    if (f.references.length > 0) {
      lines.push('**References:**', '');
      f.references.forEach((r) => lines.push(`- ${r}`));
      lines.push('');
    }
  });

  lines.push(
    '## Appendix — Methodology & Legal',
    '',
    'This assessment was performed by BugSeek AI. Active tests were rate-limited, scope-restricted to the ' +
      'user-confirmed target, and executed only after explicit authorization confirmation. Sensitive data ' +
      'discovered during testing is redacted before storage and never exfiltrated.',
    '',
    '_Disclaimer: automated findings require human verification before submission to bug bounty programs. ' +
      'BugSeek AI is intended for authorized security testing only; users accept liability for their testing activities._'
  );

  return lines.join('\n');
}
