import PDFDocument from 'pdfkit';
import type { Finding, Scan } from '../types.js';
import { SEVERITY_ORDER } from '../types.js';

export interface ReportInput {
  scan: Scan;
  findings: Finding[];
  generatedBy: string;
}

/**
 * PDF report generator (plan §3.2 reporting): executive summary, severity
 * breakdown, CVSS v3.1 estimates with justification, reproduction steps,
 * remediation advice, and methodology/authorization appendix.
 */
export function generatePdfReport(input: ReportInput): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks: Buffer[] = [];
    doc.on('data', (c: Buffer) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const { scan, findings } = input;
    const sorted = [...findings].sort(
      (a, b) => SEVERITY_ORDER[a.severity] - SEVERITY_ORDER[b.severity]
    );
    const counts: Record<string, number> = {};
    for (const f of sorted) counts[f.severity] = (counts[f.severity] ?? 0) + 1;

    // ── Cover ──
    doc.fontSize(26).fillColor('#111827').text('BugSeek AI', { align: 'left' });
    doc.fontSize(16).fillColor('#374151').text('Security Assessment Report');
    doc.moveDown();
    doc.fontSize(11).fillColor('#4b5563');
    doc.text(`Target: ${scan.targetUrl}`);
    doc.text(`Scan mode: ${scan.mode}`);
    doc.text(`Scan ID: ${scan.id}`);
    doc.text(`Scan date: ${scan.createdAt}`);
    if (scan.authorizationId) doc.text(`Authorization record: ${scan.authorizationId}`);
    doc.text(`Generated by: ${input.generatedBy}`);
    doc.moveDown();

    // ── Executive summary ──
    doc.fontSize(16).fillColor('#111827').text('Executive Summary');
    doc.fontSize(11).fillColor('#374151');
    const total = sorted.length;
    doc.text(
      `BugSeek AI performed a ${scan.mode} security assessment of ${scan.targetUrl} ` +
        `and identified ${total} finding${total === 1 ? '' : 's'}. ` +
        `CVSS v3.1 scores in this report are heuristic estimates produced by BugSeek's ` +
        `scoring model and should be validated by a human analyst before submission.`
    );
    doc.moveDown(0.5);
    doc.text(
      `Severity breakdown: ` +
        ['critical', 'high', 'medium', 'low', 'info']
          .map((s) => `${s}: ${counts[s] ?? 0}`)
          .join(' · ')
    );
    const traps = sorted.filter((f) => f.honeypotSuspect).length;
    if (traps > 0) {
      doc.fillColor('#92400e').text(
        `Note: ${traps} observation(s) were flagged as possible honeypots/traps and require manual verification.`
      );
      doc.fillColor('#374151');
    }

    // ── Findings ──
    doc.addPage();
    doc.fontSize(16).fillColor('#111827').text('Findings');
    doc.moveDown();

    if (sorted.length === 0) {
      doc.fontSize(11).fillColor('#374151').text('No findings were identified during this scan.');
    }

    for (const [idx, f] of sorted.entries()) {
      if (idx > 0) doc.moveDown();
      const sevColor: Record<string, string> = {
        critical: '#991b1b', high: '#c2410c', medium: '#92400e', low: '#1e40af', info: '#4b5563',
      };
      doc.fontSize(13).fillColor('#111827').text(`${idx + 1}. ${f.title}`);
      doc.fontSize(10).fillColor(sevColor[f.severity] ?? '#4b5563')
        .text(`Severity: ${f.severity.toUpperCase()}${f.cvssScore != null ? `  ·  CVSS: ${f.cvssScore.toFixed(1)}` : ''}  ·  Confidence: ${f.confidence}`);
      if (f.honeypotSuspect) {
        doc.fillColor('#92400e').text(`⚠ Possible trap (trap probability ${(f.trapProbability * 100).toFixed(0)}%) — verify manually before reporting.`);
      }
      doc.fillColor('#374151').fontSize(11);
      doc.moveDown(0.25);
      doc.text(f.description);
      if (f.cvssVector) {
        doc.fontSize(9).fillColor('#6b7280').text(`CVSS vector: ${f.cvssVector} (estimate)`);
        doc.fontSize(11).fillColor('#374151');
      }
      if (f.location) {
        doc.moveDown(0.25);
        doc.fontSize(10).fillColor('#111827').text('Location:');
        doc.fillColor('#374151').text(f.location);
      }
      if (f.evidence) {
        doc.moveDown(0.25);
        doc.fontSize(10).fillColor('#111827').text('Evidence (redacted):');
        doc.fillColor('#374151').font('Courier').fontSize(9).text(f.evidence);
        doc.font('Helvetica');
      }
      if (f.reproSteps.length > 0) {
        doc.moveDown(0.25);
        doc.fontSize(10).fillColor('#111827').text('Reproduction steps:');
        doc.fillColor('#374151');
        f.reproSteps.forEach((s, i) => doc.text(`${i + 1}. ${s}`));
      }
      doc.moveDown(0.25);
      doc.fontSize(10).fillColor('#111827').text('Remediation:');
      doc.fillColor('#374151').text(f.remediation);
      if (f.suggestedFix) {
        doc.moveDown(0.25);
        doc.fontSize(10).fillColor('#111827').text('Suggested fix (AI-generated — review before applying):');
        doc.fillColor('#374151').text(f.suggestedFix);
      }
      if (f.references.length > 0) {
        doc.moveDown(0.25);
        doc.fontSize(10).fillColor('#111827').text('References:');
        doc.fillColor('#374151');
        f.references.forEach((r) => doc.fillColor('#1e40af').text(r));
        doc.fillColor('#374151');
      }
    }

    // ── Appendix ──
    doc.addPage();
    doc.fontSize(16).fillColor('#111827').text('Appendix — Methodology & Legal');
    doc.fontSize(11).fillColor('#374151').moveDown(0.5);
    doc.text(
      'This assessment was performed by BugSeek AI, an AI-assisted security reconnaissance tool. ' +
        'Active tests were rate-limited, scope-restricted to the user-confirmed target, and executed only ' +
        'after explicit authorization confirmation (see authorization record above). Sensitive data discovered ' +
        'during testing is redacted before storage and never exfiltrated.'
    );
    doc.moveDown(0.5);
    doc.text(
      'Disclaimer: automated findings require human verification before submission to bug bounty programs. ' +
        'BugSeek AI is intended for authorized security testing only; users accept liability for their testing activities.'
    );

    doc.end();
  });
}
